### ISSUE TITLE
Job analysis - Chief happiness officer

### ISSUE THREAD

**Issue by atz-dev** [Jobseer/Jobseer#10]
**Tasks :**

- [x] How were they created and why
- [x] Search competences needed for these jobs
- [ ] What people who do these jobs did before and which competences were usefull for their new job
- [ ] How could we have predicted these jobs before they were created

**Comment by atz-dev** [comment]
**How they were created and why ?**
« Le bien-être est d’ailleurs un des vecteurs les plus importants de la productivité individuelle et donc collective en entreprise »
« récentes études qui démontrent toute l’importance du sentiment d’appartenance dans la motivation du personnel »
Salarié épanoui = performance
Ce poste a été créé pour répondre aux nouveaux besoins des salariés face aux profondes évolutions que les entreprises ont subies ces dernières décennies avec, notamment, la globalisation de l'outil informatique et la libéralisation des échanges
Bcp plus de sociétal dans les entreprises
Embauchés pour valoriser certains métiers ou créer du lien entre les salariés
Ont pour mission le bien-être au travail, et la convivialité
Eviter le turn-over du personnel, améliorer la productivité, réduire l’absentéisme
L’objectif est de faire en sorte que les employés aiment vraiment travailler, pour venir motivés et contents 
Après analyse de l’environnement de travail, développement du lien social en mettant en place des activités, des événements (team building, séminaires, déjeuners d’équipe, afterworks, outils de com interne, conciergerie, modification des horaires de taf,..)
Recupere du feedback

**Competences / studies needed for this job ?**
Ils rentrent dans les métiers de la fonction RH
Les profils de formations sont assez atypiques car métier récent
C’est souvent la personnalité qui conduit vers ce métier
Tous les CHO ont en commun une formation en RH ou communication et une expérience notable de l’entreprise
Niveau bac + 3 
- Licence pro en communication
- Licence pro en RH
Niveau bac + 5
- Master pro en communication
- Master pro en RH
Pour faire ce metier, il faut être convaincu de l’intérêt de la fonction avant tout, adherer au projet d’entreprise 
Avoir des qualités de synthèse, d’analyse et d’observation, être à l’écoute, organisé et inventif
Médiateur, fédérateur, communicant, convaincant, argumenté
Ce poste permet une diminution de l’absentéisme, une baisse des démissions, une augmentation en productivité et une progression des candidatures

**What people who do these jobs did before ? Which competences were useful for this new job ?**
Ils viennent souvent du secteur de la communication et des ressources humaines. 
Aujourd'hui, seules les qualités intrinsèques du candidat pouvant potentiellement inspirer le bien-être font office de curriculum vitae

**How could we have predicted this job before it was created ?**
Evolution des entreprises, et place du bien être dans le quotidien des gens

**Comment by atz-dev** [comment]
**How they were created and why ?**
« Le bien-être est d’ailleurs un des vecteurs les plus importants de la productivité individuelle et donc collective en entreprise »
« récentes études qui démontrent toute l’importance du sentiment d’appartenance dans la motivation du personnel »
Salarié épanoui = performance
Ce poste a été créé pour répondre aux nouveaux besoins des salariés face aux profondes évolutions que les entreprises ont subies ces dernières décennies avec, notamment, la globalisation de l'outil informatique et la libéralisation des échanges
Bcp plus de sociétal dans les entreprises
Embauchés pour valoriser certains métiers ou créer du lien entre les salariés
Ont pour mission le bien-être au travail, et la convivialité
Eviter le turn-over du personnel, améliorer la productivité, réduire l’absentéisme
L’objectif est de faire en sorte que les employés aiment vraiment travailler, pour venir motivés et contents 
Après analyse de l’environnement de travail, développement du lien social en mettant en place des activités, des événements (team building, séminaires, déjeuners d’équipe, afterworks, outils de com interne, conciergerie, modification des horaires de taf,..)
Recupere du feedback

**Competences / studies needed for this job ?**
Ils rentrent dans les métiers de la fonction RH
Les profils de formations sont assez atypiques car métier récent
C’est souvent la personnalité qui conduit vers ce métier
Tous les CHO ont en commun une formation en RH ou communication et une expérience notable de l’entreprise
Niveau bac + 3 
- Licence pro en communication
- Licence pro en RH
Niveau bac + 5
- Master pro en communication
- Master pro en RH
Pour faire ce metier, il faut être convaincu de l’intérêt de la fonction avant tout, adherer au projet d’entreprise 
Avoir des qualités de synthèse, d’analyse et d’observation, être à l’écoute, organisé et inventif
Médiateur, fédérateur, communicant, convaincant, argumenté
Ce poste permet une diminution de l’absentéisme, une baisse des démissions, une augmentation en productivité et une progression des candidatures

**What people who do these jobs did before ? Which competences were useful for this new job ?**
Ils viennent souvent du secteur de la communication et des ressources humaines. 
Aujourd'hui, seules les qualités intrinsèques du candidat pouvant potentiellement inspirer le bien-être font office de curriculum vitae

**How could we have predicted this job before it was created ?**
Evolution des entreprises, et place du bien être dans le quotidien des gens
