### ISSUE TITLE
Job analysis - Applications developper

### ISSUE THREAD

**Issue by atz-dev** [Jobseer/Jobseer#11]
**Tasks :**

- [ ] How they were created and why ?
- [ ] Competences / studies needed for this job ?
- [ ] What people who do these jobs did before ? Which competences were useful for this new job ?
- [ ] How could we have predicted this job before it was created ?

**Comment by BariantB** [comment]
Applications developper a été crée vers la démocratisation des smartphone et des ordinateurs portables
La mission d’un Développeur d’applications, est de créer, améliorer des programmes informatiques ou encore d’adapter des logiciels existants à la demande particulière de son client.
Très technique, la fonction requiert la connaissance des langages de programmation, des logiciels, du fonctionnement des réseaux et connaître la modélisation UML.Autonomie, imagination, réactivité, écoute, rigueur et précision,sont des qualités indispensables à ce métier.
Pour les études on peut passer par un Bac +2 ( DUT MMI / DUT informatique) ou par un Bac +3/+5 (licence pro / master)
Avant que des personnes ne travaille comme Applications developper ils étaient développeur/développeur web et ils avaient comme compétences : connaissance en techniques et technologies du web, culture du web et connaissance des langages de programmation.
On aurait pu prédire ce métiers en se penchant sur la démocratisation des objets électroniques tel que le smartphone ou bien encore l'ordinateur portable
