### ISSUE TITLE
Job analysis - UX/UI Designer

### ISSUE THREAD

**Issue by atz-dev** [Jobseer/Jobseer#12]
**Tasks :**

- [ ] How they were created and why ?
- [ ] Competences / studies needed for this job ?
- [ ] What people who do these jobs did before ? Which competences were useful for this new job ?
- [ ] How could we have predicted this job before it was created ?

**Comment by BariantB** [comment]
UX/UI designer a été crée vers la sortie des premier téléphones tactile/ tablettes
Ce métier a pour objectif de rendre la navigation en ligne plus facile et intuitive, d'organiser le contenue et apporter une meilleur expérience utilisateur.
Les compétences nécessaires sont: culture web approfondie et une bonne compréhension des tendances, connaissances techniques de technologies front-end, maitriser des logiciels graphique, créativité
Pour les études on peut passer par un Bac +2 ( DUT MMI / DUT informatique) ou par un Bac +3/+5 (licence pro / d'école d'art ou de design)
Avant que des personnes ne travails comme UX/UI designer ils étaient développeur web et ils avaient comme compétences : connaissance en techniques et technologies du web, culture du web.
On aurait pu prédire ce métiers en se penchant sur les nouvelles technologies (nouvelle taille d'écran/ écran tactile/ accès a internet)
