### ISSUE TITLE
Job analysis - Video game player (streamers, competitors, etc)

### ISSUE THREAD

**Issue by atz-dev** [Jobseer/Jobseer#17]
**Tasks :**

- [ ] How they were created and why ?
- [ ] Competences / studies needed for this job ?
- [ ] What people who do these jobs did before ? Which competences were useful for this new job ?
- [ ] How could we have predicted this job before it was created ?

**Comment by atz-dev** [comment]
**How they were created and why ?**
La creation de ce metier provient majoritairement des scenes du jeu vidéo telles que Youtube.
Au départ, ces joueurs étaient pour la plupart des vidéastes et se sont convertis en joueurs professionnels lorsque ces disciplines ont été reconnues comme des sports à part entière (e-sport).
Aujourd’hui, de nombreux joueurs font parti de structures professionnelles dédiées au jeu vidéo en compétition.
Une grande partie d’entre eux sont aussi sur des plateformes de diffusion en direct comme Twitch, qui permet à leur public d’interagir avec eux. De ce fait, ils peuvent créer leur propre communauté, souvent constituées de jeunes joueurs qui souhaites s’améliorer en regardant des joueurs pro, qui rêvent aussi parfois d’être sur la scène compétitive comme pour d’autres sports auparavant. Au final c’est le mix parfait entre un element intemporel, le sport et l’esprit de compétition, avec un élément des temps actuels, le jeu vidéo.

**Competences / studies needed for this job ?**
Auparavant, la plupart des joueurs pro ou qui diffusent sur des plateformes de streaming n’avaient pas d’autres études que le temps passé sur leur pc / console. Au niveau des études, pas de cursus particulier.
Mais aujourd’hui, des écoles de e-sport, de vidéaste ou de streamer émergent : c’est le cas pour l’école XP, membre du groupe IONIS dont fait parti Epitech, l’école Gaming Campus, Helios Gaming School, Montpellier Gaming Academy ou d’autres. Ces écoles ont pour objectif de transformer les passionnés de jeu vidéo en vrai professionnels de l’audio visuel, en leur apportant à la fois un bagage en communication, community management, événementiel, marketing, mais aussi des entrainements pour devenirs des athletes de haut niveau dans leur discipline, des partenariats avec de grosses structures ou équipes, etc.

**What people who do these jobs did before ? Which competences were useful for this new job ?**
Les personnes exerçant ces métiers sont tous très jeune : il n’y a donc pas vraiment d’antecedent. 
En tout cas, une experience en communication, en theatre, en audiovisuel sont des pistes qui peuvent grandement améliorer le profil d’un candidat. Meme si ce qui prime est sa passion,  son talent et son aptitude a captiver un public, sa singularité.

**How could we have predicted this job before it was created ?**
Nous aurions pu faire le lien entre les sports que nous connaissions deja auparavant, l’importance que la diffusion de ceux-ci possède, et la nouvelle scene émergente du jeu video, ainsi que son aspect compétitif très fort.
